apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: admin
  MONGO_INITDB_ROOT_PASSWORD: admin123
  MONGODB_URI: mongodb://admin:admin123@mongodb:27017/tutorialdb?authSource=admin
